[package]
name = "TtTorrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
urlencoding = "2.1.3"
sha1 = "0.10.6"
reqwest = { version = "0.11.20", features = ["blocking"]}
percent-encoding = "2.3.0"
http = "0.2.9"
byteorder = "1.4.3"
tokio = {versio = "1.33.0", features = ["full"]} 
